parameters:
- name: vmImageName
  type: string
  default: ubuntu-latest
  values:
  - windows-2022
  - windows-2019
  - windows-latest
  - ubuntu-20.04
  - ubuntu-18.04
  - ubuntu-latest
  - macOS-11
  - macOS-10.15
  - macOS-10.14
  - macOS-latest
  
stages:
  - stage: Build
    pool:
      vmImage: ${{ parameters.vmImageName }}
    displayName: Build and Test

    jobs:
    - job: Build
        
      steps:
        - template: dotnet-use.yml@templates

        - template: dotnet-restore.yml@templates
        
        - template: dotnet-build.yml@templates
        
        - template: dotnet-test.yml@templates
          parameters:
            testsPath: '**/*Tests.csproj'

  - stage: SonarQube
    dependsOn: Build
    condition: succeeded()
    displayName: SonarQube
    jobs:  
    - job: SonarQube
      displayName: SonarQube
      steps:
        - template: sonarqube-v1.yml@templates
          parameters:
            serverEndpoint: sonarqube-prd
            projectName: 'MVPConf.ProjectOne'
            projectKey: MVPConf-2021-v1_MVPConf.ProjectOne

  - stage: Docker_Build
    dependsOn: SonarQube
    condition: succeeded()
    displayName: ACR Build And Push
    jobs:  
    - job: ACR_Build_And_Push
      displayName: ACR Build And Push
      steps:
        - template: acr.yml@templates
          parameters:
            imageRepository: project-one
            dockerfilePath: '**/*Dockerfile'
            acrServiceConnection: acr-mvpconf2021-dev

  - stage: Deploy
    displayName: Deploy
    dependsOn:
    - Docker_Build
    condition: succeeded()
    jobs:
    - deployment: Deploy
      displayName: Deploy Container on WebApp
      environment: 'MVPConf-2021-DevOps'
      variables:
        - group: 'Global-Library'
      pool:
        vmImage: ${{ parameters.vmImageName }}
      strategy:
        runOnce:
          deploy:
            steps:
              - template: webapp.yml@templates
                parameters:
                  webappName: app-mvpconf2021-dev
                  serviceConnectionAzure: rg-mvpconf2021-dev
                  containerRegistry: $(containerRegistry)
                  imageRepository: project-one
                  resourceGroup: rg-mvpconf2021-dev